# paicar_lr_model.py
# Auto-generated by train_paicar_lr.py
# Linear Regression model for PAI-Car

FEATURE_COLUMNS = ['n0', 'n1', 'n2', 'n3', 'n4', 'n5', 'n6', 'n7', 'position', 'error', 'd_error', 'base_speed']
TARGET_COLUMNS = ['left_cmd', 'right_cmd']

COEF = [
    [-0.1251989049, -0.05319570911, -0.05009077957, 0.2492324421, 0.2344092105, 0.01187846186, -0.1629489486, -0.004176232161, 0.1502584397, 0.1602227292, 0.08501148825, -0.00284693986],
    [-0.1059818867, -0.02987401621, -0.03987390274, 0.2558148222, 0.2407538632, 0.005998893477, -0.1716648295, -0.01524317744, 0.1091354769, -0.3346879542, -0.1028400097, 0.1268066946],
]

INTERCEPT = [-2.84693986e-06, 0.0001268066946]

def predict(features):
    """
    features:
        [n0,n1,n2,n3,n4,n5,n6,n7,position,error,d_error,base_speed]

    return:
        left_cmd, right_cmd
    """
    out = []
    for j in range(len(COEF)):
        y = INTERCEPT[j]
        for i in range(len(features)):
            y += COEF[j][i] * features[i]
        out.append(y)
    return out[0], out[1]
