# paicar_lr_model.py
# Auto-generated by train_paicar_lr.py
# Linear Regression model for PAI-Car

FEATURE_COLUMNS = ['n0', 'n1', 'n2', 'n3', 'n4', 'n5', 'n6', 'n7', 'position', 'error', 'd_error', 'base_speed']
TARGET_COLUMNS = ['left_cmd', 'right_cmd']

COEF = [
    [0.04194702066, -0.02445492494, -0.00821990512, 0.03403486869, 0.02886314636, 0.07603866752, -0.03902078828, -0.149627295, 0.1859614717, -0.00357173395, 0.1708880056, 0.0400727349],
    [-0.1149090864, -0.07866042524, 0.03920156414, 0.06077750402, 0.01904204602, 0.04734781086, 0.007574775931, 0.029997502, 0.1662548858, -0.3747258417, -0.1491529307, 0.1143787824],
]

INTERCEPT = [5.415234446e-05, 0.0001545659221]

def predict(features):
    """
    features:
        [n0,n1,n2,n3,n4,n5,n6,n7,position,error,d_error,base_speed]

    return:
        left_cmd, right_cmd
    """
    out = []
    for j in range(len(COEF)):
        y = INTERCEPT[j]
        for i in range(len(features)):
            y += COEF[j][i] * features[i]
        out.append(y)
    return out[0], out[1]
