# train_paicar_lr.py
# PAI-Car Linear Regression model training
#
# 기능:
#   1. logs 폴더의 최신 CSV 파일을 읽는다.
#   2. 주행 데이터 중 학습에 적합한 행만 골라낸다.
#   3. Linear Regression으로 left_cmd, right_cmd를 학습한다.
#   4. 학습 결과를 Pico에서 import 가능한 paicar_lr_model.py로 저장한다.
#
# 실행:
#   python train_paicar_lr.py

import os
import glob
import numpy as np
import pandas as pd


# ------------------------------------------------------------
# Settings
# ------------------------------------------------------------

LOG_DIR = "logs"

# 특정 파일을 직접 지정하고 싶으면 여기에 파일명을 넣는다.
# 예:
# CSV_FILE = "logs/pai_car_run_20260705_174230.csv"
CSV_FILE = None

MODEL_OUT = "pai_car_lr_model.py"

FEATURE_COLUMNS = [
    "n0", "n1", "n2", "n3", "n4", "n5", "n6", "n7",
    "position",
    "error",
    "d_error",
    "base_speed",
]

TARGET_COLUMNS = [
    "left_cmd",
    "right_cmd",
]

# T 마커 구간은 일반 라인트레이싱 데이터와 성격이 다르므로 기본 제외
EXCLUDE_MARKER = True

# 라인을 잃은 구간은 error가 마지막 position 기준일 수 있으므로 제외
EXCLUDE_OFF_LINE = True


# ------------------------------------------------------------
# Utility
# ------------------------------------------------------------

def find_latest_csv(log_dir):
    files = glob.glob(os.path.join(log_dir, "*.csv"))

    if not files:
        raise FileNotFoundError("No CSV files found in '{}'".format(log_dir))

    files.sort(key=os.path.getmtime, reverse=True)
    return files[0]


def load_csv():
    if CSV_FILE is None:
        csv_path = find_latest_csv(LOG_DIR)
    else:
        csv_path = CSV_FILE

    print("CSV file:", csv_path)

    df = pd.read_csv(csv_path)
    return df, csv_path


def filter_data(df):
    before = len(df)

    # 필요한 컬럼 확인
    required = FEATURE_COLUMNS + TARGET_COLUMNS + ["on_line", "is_marker"]

    for col in required:
        if col not in df.columns:
            raise ValueError("Missing column: {}".format(col))

    # 숫자형 변환
    for col in required:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    df = df.dropna()

    if EXCLUDE_OFF_LINE:
        df = df[df["on_line"] == 1]

    if EXCLUDE_MARKER:
        df = df[df["is_marker"] == 0]

    after = len(df)

    print("Rows before filter:", before)
    print("Rows after  filter:", after)

    if after < 20:
        raise ValueError("Too few rows for training. Collect more driving data.")

    return df


def train_linear_regression_numpy(X, y):
    """
    sklearn 없이 numpy만으로 다중 출력 Linear Regression 학습.

    y = X @ coef + intercept

    반환:
        coef      shape = (target_count, feature_count)
        intercept shape = (target_count,)
    """

    # bias 항 추가
    ones = np.ones((X.shape[0], 1), dtype=np.float64)
    Xb = np.hstack([ones, X])

    # 최소제곱해
    # W shape = (feature_count + 1, target_count)
    W, residuals, rank, s = np.linalg.lstsq(Xb, y, rcond=None)

    intercept = W[0, :]
    coef = W[1:, :].T

    return coef, intercept


def predict_linear(X, coef, intercept):
    return X @ coef.T + intercept


def calc_metrics(y_true, y_pred):
    err = y_pred - y_true

    mae = np.mean(np.abs(err), axis=0)
    rmse = np.sqrt(np.mean(err ** 2, axis=0))

    ss_res = np.sum(err ** 2, axis=0)
    ss_tot = np.sum((y_true - np.mean(y_true, axis=0)) ** 2, axis=0)

    r2 = 1.0 - ss_res / ss_tot

    return mae, rmse, r2


def split_train_test(X, y, test_ratio=0.2):
    """
    시간 순서를 어느 정도 유지하기 위해 단순 랜덤 셔플 대신
    전체 데이터를 일정 간격으로 나눠 test를 뽑는다.
    """

    n = len(X)

    indices = np.arange(n)
    test_step = int(1.0 / test_ratio)

    test_mask = (indices % test_step) == 0
    train_mask = ~test_mask

    return (
        X[train_mask],
        X[test_mask],
        y[train_mask],
        y[test_mask],
    )


def save_model_py(model_path, feature_columns, target_columns, coef, intercept):
    """
    Pico에서 import 가능한 Python 모듈로 저장한다.
    """

    with open(model_path, "w", encoding="utf-8") as f:
        f.write("# paicar_lr_model.py\n")
        f.write("# Auto-generated by train_paicar_lr.py\n")
        f.write("# Linear Regression model for PAI-Car\n\n")

        f.write("FEATURE_COLUMNS = {}\n".format(repr(feature_columns)))
        f.write("TARGET_COLUMNS = {}\n\n".format(repr(target_columns)))

        f.write("COEF = [\n")
        for row in coef:
            f.write("    [")
            f.write(", ".join("{:.10g}".format(float(v)) for v in row))
            f.write("],\n")
        f.write("]\n\n")

        f.write("INTERCEPT = [")
        f.write(", ".join("{:.10g}".format(float(v)) for v in intercept))
        f.write("]\n\n")

        f.write("def predict(features):\n")
        f.write("    \"\"\"\n")
        f.write("    features:\n")
        f.write("        [n0,n1,n2,n3,n4,n5,n6,n7,position,error,d_error,base_speed]\n")
        f.write("\n")
        f.write("    return:\n")
        f.write("        left_cmd, right_cmd\n")
        f.write("    \"\"\"\n")
        f.write("    out = []\n")
        f.write("    for j in range(len(COEF)):\n")
        f.write("        y = INTERCEPT[j]\n")
        f.write("        for i in range(len(features)):\n")
        f.write("            y += COEF[j][i] * features[i]\n")
        f.write("        out.append(y)\n")
        f.write("    return out[0], out[1]\n")

    print("Model saved:", model_path)


# ------------------------------------------------------------
# Main
# ------------------------------------------------------------

def main():
    df, csv_path = load_csv()
    df = filter_data(df)

    X = df[FEATURE_COLUMNS].to_numpy(dtype=np.float64)
    y = df[TARGET_COLUMNS].to_numpy(dtype=np.float64)

    X_train, X_test, y_train, y_test = split_train_test(X, y, test_ratio=0.2)

    coef, intercept = train_linear_regression_numpy(X_train, y_train)

    y_train_pred = predict_linear(X_train, coef, intercept)
    y_test_pred = predict_linear(X_test, coef, intercept)

    train_mae, train_rmse, train_r2 = calc_metrics(y_train, y_train_pred)
    test_mae, test_rmse, test_r2 = calc_metrics(y_test, y_test_pred)

    print()
    print("Features:", FEATURE_COLUMNS)
    print("Targets :", TARGET_COLUMNS)
    print()

    print("Train rows:", len(X_train))
    print("Test rows :", len(X_test))
    print()

    print("Train MAE left/right :", train_mae)
    print("Train RMSE left/right:", train_rmse)
    print("Train R2 left/right  :", train_r2)
    print()

    print("Test MAE left/right  :", test_mae)
    print("Test RMSE left/right :", test_rmse)
    print("Test R2 left/right   :", test_r2)
    print()

    print("Intercept:")
    print(intercept)
    print()

    print("Coef:")
    print(coef)
    print()

    save_model_py(
        MODEL_OUT,
        FEATURE_COLUMNS,
        TARGET_COLUMNS,
        coef,
        intercept
    )


if __name__ == "__main__":
    main()