# paicar_lr_model.py
# Auto-generated by train.py
# Ridge Linear Regression model for PAI-Car
# Predicts left_cmd, right_cmd from telemetry/profile features.

MODEL_KIND = 'ridge_linear_regression'
RIDGE_ALPHA = 10
MOTOR_MIN = -300
MOTOR_MAX = 1000

FEATURE_COLUMNS = ['n0', 'n1', 'n2', 'n3', 'n4', 'n5', 'n6', 'n7', 'position', 'error', 'd_error', 'base_speed', 'actual_section_id', 'active_profile_id', 'profile_version', 'profile_base_speed', 'profile_curve_speed', 'profile_sharp_curve_speed', 'profile_min_run_speed', 'profile_kp', 'profile_kd', 'profile_max_correction', 'profile_reverse_allow', 'profile_reverse_pwm_mid', 'profile_reverse_pwm_high', 'profile_error_curve_threshold', 'profile_error_sharp_threshold', 'profile_d_error_curve_threshold', 'profile_d_error_sharp_threshold', 'profile_search_pwm', 'profile_line_loss_max_ms']
TARGET_COLUMNS = ['left_cmd', 'right_cmd']

FEATURE_MEAN = [
    96.7824187824, 137.537537538, 293.684138684, 777.095277095, 767.961779962, 279.102648103, 129.864591865, 70.5986895987, 3456.8034398, -43.1965601966, -1.63882063882, 989.781599782, 4.80944580945, 2.0586950587, 5.49030849031, 998.386568387, 959.942669943, 859.241059241, 581.706251706, 0.551384111384, 0.21690963691, 960.810810811, 0.605241605242, -51.3022113022, -131.919191919, 1754.34070434, 2917.14441714, 1292.58804259, 2160.68796069, 279.822549823, 247.54026754
]

FEATURE_SCALE = [
    149.143445351, 228.43555618, 355.358957127, 309.429426454, 306.271868975, 340.770384866, 230.431977415, 121.450160289, 837.205397796, 837.205397796, 178.305534248, 31.9415641705, 2.96282330136, 1.03162927343, 0.499906065816, 9.81906499856, 39.7009293271, 73.1881709432, 20.0193458634, 0.00854533853133, 0.0180530438274, 67.9481501105, 0.488798736216, 54.3597194842, 114.618630874, 245.495027592, 325.804965284, 225.095160121, 277.416450613, 18.2333634835, 28.2733517939
]

COEF = [
    [1.60351112763, -55.6788119666, -57.8391224512, 40.7494348481, 64.3985683188, -3.3100801698, -12.2320433603, 10.4370699582, 69.6328759938, 69.6328759938, 23.1385315747, 33.3261618, 0.580547443155, 4.24526470107, 0.691800009147, 0.679713002698, 5.89363460516, 1.74820296669, -1.33456093862, -5.22313331601, 0.215516559488, 2.24032175639, -4.04873471156, 1.97825254884, 3.55290501477, -2.98265925983, -7.47948356442, -5.18779328036, -5.96810299259, -8.17926236896, -9.14962616512],
    [9.61648716392, -14.3872724903, -21.1015767119, 72.7737784309, 37.0688514948, -40.4081348522, -56.6928940064, 14.187285751, -79.0705691201, -79.0705691201, -17.5514679413, 31.2359403985, 3.15279938773, 13.482019622, 2.28149272344, 0.0268807599089, 7.6793973344, 0.867509734372, -8.86777297053, -5.68170456847, -0.663203873883, 0.0996698450242, -2.66109197494, 2.69362613548, 3.47533188459, -3.62640161873, -8.14312368254, -3.70908472926, -5.07077517958, -12.16677373, -14.7724843794],
]

INTERCEPT = [830.612339612, 856.343980344]

def _to_float(v, default=0.0):
    try:
        if v is True:
            return 1.0
        if v is False:
            return 0.0
        return float(v)
    except Exception:
        return default

def _clamp(v, vmin, vmax):
    if v > vmax:
        return vmax
    if v < vmin:
        return vmin
    return v

def _get_feature(features, index, name):
    if isinstance(features, dict):
        return _to_float(features.get(name, 0.0))
    if index >= len(features):
        return 0.0
    return _to_float(features[index])

def predict_raw(features):
    """
    features can be either:
      1. list/tuple in FEATURE_COLUMNS order
      2. dict with keys in FEATURE_COLUMNS
    returns float left_cmd, right_cmd without clamp
    """
    out = []
    for j in range(len(COEF)):
        y = INTERCEPT[j]
        for i in range(len(FEATURE_COLUMNS)):
            name = FEATURE_COLUMNS[i]
            x = _get_feature(features, i, name)
            x = (x - FEATURE_MEAN[i]) / FEATURE_SCALE[i]
            y += COEF[j][i] * x
        out.append(y)
    return out[0], out[1]

def predict(features, motor_min=MOTOR_MIN, motor_max=MOTOR_MAX):
    """returns int left_cmd, right_cmd with clamp"""
    left, right = predict_raw(features)
    left = _clamp(left, motor_min, motor_max)
    right = _clamp(right, motor_min, motor_max)
    return int(left), int(right)
